
version: '3'

services:
  alice:
    build: ./alice
    image: alice:1.0
    container_name: alice
    ports:
      - '8080:8080'
    depends_on:
      - bob
  bob:
    build: ./bob
    ports:
      - '8081:8081'